:linkattrs:

= Overview

The configuration and code changes that are done to spring boot based _Ola_ application when deploying on to https://istio.io/[Istio] configured
environment.

NOTE: This application works only on Kubernetes Cluster as OpenShift does not yet support Istio

== Pre-requisites

* https://istio.io/[Istio] is configured and running in your environment
* istioctl binary is available in local path where build will be executed

== What becomes deprecated ?

When deploying with Istio we might not need the explicit tracing related
code to be added in the application business logic, the code just need to propogate
the headers listed below as part of each request.  The Istio will take care of sending the
spans/traces associated with the headers to Zipkin

NOTE: Refer to the commented code in *TracingConfiguration* and *OlaController* for changes related to header propagation

== What you need ?

=== Tracing

As mentioned in previous sections the following are the headers that needs to be propagated with
each request that needs to be traced:

- x-request-id
- x-b3-traceid
- x-b3-spanid
- x-b3-parentspanid
- x-b3-sampled
- x-b3-flags
- x-ot-span-context

=== Circuit Breakers

To enable circuit breakers we need to create Istio https://istio.io/docs/reference/config/traffic-rules/routing-rules.html[route-rule] and
https://istio.io/docs/reference/config/traffic-rules/destination-policies.html[destination-policy]

For this demo we will create the following route-rule and destination-policy

[code,yaml]
----

---
type: route-rule
name: ola-default-route
spec:
  destination: ola.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: "0.0.2" <1>
    weight: 100

---
type: destination-policy
name: ola-default-cb
spec:
  destination: ola.default.svc.cluster.local
  policy:
  - tags:
      version: "0.0.2" <1>
    circuitBreaker:
      simpleCb:
        maxConnections: 1 <2>
        httpMaxRequestsPerConnection: 1 <3>
        sleepWindow: 30s <4>
        httpDetectionInterval: 1m <5>
----

<1> the Kubernetes deployment tag that will be used to identify the backend service version
and we apply the destination policy to the same version
<2> maximum number of allowed connections, kept it small for demo
<3> how many requests are allowed per connection, in this demo we allow only request per connection
i.e. keep-alive is *off*
<4> circuit breaker open window time
<5> time interval to check the status of circuit

== Build and Deploy

[[build]]
=== Build
[code,sh]
----
./mvnw clean install
----

[[deploy]]
=== Deploy

The build above should create the required kubernetes manifests that allows to deploy the service in Istio Service Mesh.
All the files will be located in the *target* directory of the project

[code,sh]
----

kubectl apply -f /target/istio/isito-ola.yaml <1>

----

<1> Deploy the _ola_ in to kubernetes cluster and create the _ola_ service
[test]]

== Testing

Since the destination policy has defined the Circuit Breaker, the application should return the client
with errors post 2 requests which means 90% failure for concurrent requests of 20 users.

The application url can be found using the command `echo $(minikube ip):$(kubectl get svc istio-ingress -o jsonpath='{.spec.ports[0].nodePort}')/httbin/delay`

To test application with concurrency you can using tools like http://gatling.io/[Gatling], the following load test script
could be used with gatling

[code,scala]
----

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class OlaServiceSimulation extends Simulation {

	val httpProtocol = http
		.baseURL("http://192.168.99.100:30420") <1>
		.inferHtmlResources()
		.acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:52.0) Gecko/20100101 Firefox/52.0")

	val headers_0 = Map("Upgrade-Insecure-Requests" -> "1")

    val uri1 = "http://192.168.99.100:30420/api/ola-long" <1>

	val scn = scenario("OlaServiceSimulation")
		.exec(http("request_0")
			.get("/api/ola-long")
			.headers(headers_0))

	setUp(scn.inject(atOnceUsers(20))).protocols(httpProtocol)
}

----

<1> replace it with Kubernetes cluster IP and isito-ingress node port

=== Executing Test Simulations

By default the gatling tests are disabled, they can be enabled passing `-Dskip.gatlingTest=false`
system property to the maven command as shown below,

[code,sh]
----
./mvnw -Dskip.gatlingTests=false gatling:integration-test
----

== References

- https://istio.io/[Istio]
- https://istio.io/docs/tasks/integrating-services-into-istio.html[Integrating to Service Mesh]
- https://istio.io/docs/tasks/zipkin-tracing.html[Distributed Tracing with Istio]





