##################################################################################################
#  Ola
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ola
  labels:
    app: istio-ola
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: istio-ola
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ola
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-ola
        version: "0.0.1"
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        - name: AB_OFF
          value: ""
        name:  spring-boot
        image: istio-ola:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
